### ISSUE TITLE
pom的依赖需要更新了，java的demo中org.bouncycastle需要更新

### ISSUE THREAD

**Issue by liciciyi** [AliwareMQ/mqtt-demo#1]
<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.70</version>
</dependency>

**Comment by LipGallager** [comment]
好人啊，一生八胎！！！！ 我这边直接贴导入的包！ 感谢你
`
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.70</version>
</dependency>
`

**Comment by DongyuanPan** [comment]
fix
